<?
$aMenuLinks = Array(
    Array(
        "Вопросы и ответы ",
        "/community/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Блоги",
        "/community/blogs/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Эксперты",
        "/community/experts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Категории",
        "/community/categories/",
        Array(),
        Array(),
        ""
    ),
);